import { Case } from "./types";

export const MOCK_CASES: Case[] = [
  {
    id: "case-001",
    foreignerName: "Nguyen Van A",
    companyName: "ABC 제조",
    visaType: "E-7 변경",
    status: "collecting",
    currentStep: 1,
    stepProgress: "제출 서류 7/9 완료",
    createdAt: "2025-01-28",
    lastUpdated: "2025-02-01 10:30",
  },
  {
    id: "case-002",
    foreignerName: "김철수",
    companyName: "테크놀로지",
    visaType: "E-7 연장",
    status: "writing",
    currentStep: 2,
    stepProgress: "고용사유서 작성 필요",
    createdAt: "2025-01-25",
    lastUpdated: "2025-02-01 09:15",
  },
  {
    id: "case-003",
    foreignerName: "John Smith",
    companyName: "글로벌 무역",
    visaType: "E-7 신규",
    status: "ready",
    currentStep: 3,
    stepProgress: "최종 출력 단계",
    createdAt: "2025-01-20",
    lastUpdated: "2025-01-31 16:45",
  },
  {
    id: "case-004",
    foreignerName: "Wang Xiaoming",
    companyName: "디지털 솔루션",
    visaType: "E-7 변경",
    status: "revision",
    currentStep: 1,
    stepProgress: "사업체 서류 보완 필요",
    createdAt: "2025-01-22",
    lastUpdated: "2025-01-30 14:20",
  },
  {
    id: "case-005",
    foreignerName: "Park Minji",
    companyName: "바이오 연구소",
    visaType: "E-7 연장",
    status: "collecting",
    currentStep: 1,
    stepProgress: "제출 서류 5/9 완료",
    createdAt: "2025-01-26",
    lastUpdated: "2025-02-01 08:00",
  },
  {
    id: "case-006",
    foreignerName: "Ahmed Hassan",
    companyName: "건설 엔지니어링",
    visaType: "E-7 신규",
    status: "completed",
    currentStep: 3,
    stepProgress: "케이스 완료",
    createdAt: "2025-01-15",
    lastUpdated: "2025-01-29 11:30",
  },
  {
    id: "case-007",
    foreignerName: "李明",
    companyName: "식품 가공",
    visaType: "E-7 변경",
    status: "writing",
    currentStep: 2,
    stepProgress: "직무기술서 작성 중",
    createdAt: "2025-01-24",
    lastUpdated: "2025-01-31 15:10",
  },
  {
    id: "case-008",
    foreignerName: "Sarah Johnson",
    companyName: "교육 컨설팅",
    visaType: "E-7 연장",
    status: "ready",
    currentStep: 3,
    stepProgress: "최종 출력 대기",
    createdAt: "2025-01-18",
    lastUpdated: "2025-01-30 10:00",
  },
];